from __future__ import annotations

from coma_engine.actions.models import ActionTemplate, TargetSignature


ACTION_TEMPLATES: dict[str, ActionTemplate] = {
    "FORAGE": ActionTemplate(
        action_type="FORAGE",
        signature=TargetSignature(required_targets=("target_tile_id",)),
        default_priority_class="survival",
        default_duration_type="instant",
        default_duration=1,
        availability_rule_id="basic_survival",
        visibility_strength=12.0,
        partial_refund_rate=0.0,
    ),
    "MOVE": ActionTemplate(
        action_type="MOVE",
        signature=TargetSignature(required_targets=("target_tile_id",)),
        default_priority_class="survival",
        default_duration_type="travel",
        default_duration=2,
        availability_rule_id="movement",
        visibility_strength=16.0,
        interruption_threshold=70.0,
    ),
    "SCOUT": ActionTemplate(
        action_type="SCOUT",
        signature=TargetSignature(required_targets=("target_tile_id",)),
        default_priority_class="survival",
        default_duration_type="travel",
        default_duration=2,
        availability_rule_id="scouting",
        visibility_strength=10.0,
        interruption_threshold=75.0,
    ),
    "TRADE": ActionTemplate(
        action_type="TRADE",
        signature=TargetSignature(required_targets=("target_settlement_id",)),
        default_priority_class="civic",
        default_duration_type="travel",
        default_duration=2,
        availability_rule_id="trade",
        visibility_strength=14.0,
        interruption_threshold=70.0,
    ),
    "MIGRATE": ActionTemplate(
        action_type="MIGRATE",
        signature=TargetSignature(required_targets=("target_tile_id",)),
        default_priority_class="survival",
        default_duration_type="travel",
        default_duration=3,
        availability_rule_id="migrate",
        visibility_strength=20.0,
        interruption_threshold=65.0,
    ),
    "FOUND_POLITY": ActionTemplate(
        action_type="FOUND_POLITY",
        signature=TargetSignature(required_targets=("target_settlement_id",)),
        default_priority_class="political",
        default_duration_type="scheme",
        default_duration=3,
        availability_rule_id="found_polity",
        visibility_strength=25.0,
        interruption_threshold=55.0,
        partial_refund_rate=0.25,
    ),
    "FORMAL_TAX_ORDER": ActionTemplate(
        action_type="FORMAL_TAX_ORDER",
        signature=TargetSignature(required_targets=("target_settlement_id",)),
        default_priority_class="civic",
        default_duration_type="instant",
        default_duration=1,
        availability_rule_id="formal_tax_order",
        visibility_strength=18.0,
        command_subject="formal_tax_order",
    ),
    "LEVY_RESOURCES": ActionTemplate(
        action_type="LEVY_RESOURCES",
        signature=TargetSignature(required_targets=("target_settlement_id",)),
        default_priority_class="civic",
        default_duration_type="channeling",
        default_duration=2,
        availability_rule_id="levy_resources",
        visibility_strength=20.0,
        command_subject="resource_levy",
    ),
    "ALLOCATE_RESOURCES": ActionTemplate(
        action_type="ALLOCATE_RESOURCES",
        signature=TargetSignature(required_targets=("target_settlement_id",)),
        default_priority_class="civic",
        default_duration_type="instant",
        default_duration=1,
        availability_rule_id="allocate_resources",
        visibility_strength=18.0,
        command_subject="resource_allocation",
    ),
    "DECLARE_WAR": ActionTemplate(
        action_type="DECLARE_WAR",
        signature=TargetSignature(required_targets=("target_polity_id",)),
        default_priority_class="war",
        default_duration_type="instant",
        default_duration=1,
        availability_rule_id="declare_war",
        visibility_strength=30.0,
    ),
    "MUSTER_FORCE": ActionTemplate(
        action_type="MUSTER_FORCE",
        signature=TargetSignature(required_targets=("target_settlement_id",)),
        default_priority_class="war",
        default_duration_type="channeling",
        default_duration=2,
        availability_rule_id="muster_force",
        visibility_strength=22.0,
        command_subject="muster_force",
    ),
    "SUPPRESS_UNREST": ActionTemplate(
        action_type="SUPPRESS_UNREST",
        signature=TargetSignature(required_targets=("target_settlement_id",)),
        default_priority_class="civic",
        default_duration_type="channeling",
        default_duration=2,
        availability_rule_id="suppress_unrest",
        visibility_strength=24.0,
        command_subject="suppress_unrest",
    ),
}
